return PlaceObj('ModDef', {
	'title', "Nice Weapon Mod - Beta",
	'description', "The mod change weapon modifications system.",
	'image', "Mod/bLYLN41/Images/Screenshot 01.png",
	'id', "bLYLN41",
	'author', "Jack_Mantel",
	'version', 1080,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'bin_assets', true,
	'code', {
		"Code/Change_Caliber_556.lua",
		"Code/Change_Caliber_762NATO.lua",
		"Code/Change_Caliber_762WP.lua",
		"Code/ReduceAimAccuracy.lua",
		"Code/ReduceAutoFireAccuracy.lua",
		"InventoryItem/Galil.lua",
		"InventoryItem/G36.lua",
		"InventoryItem/FAMAS.lua",
		"InventoryItem/AR15.lua",
		"InventoryItem/AK74.lua",
		"InventoryItem/AK47.lua",
		"InventoryItem/Bereta92.lua",
		"InventoryItem/ColtAnaconda.lua",
		"InventoryItem/Glock18.lua",
		"InventoryItem/HiPower.lua",
		"InventoryItem/DesertEagle.lua",
		"InventoryItem/ColtPeacemaker.lua",
		"InventoryItem/MP5.lua",
		"InventoryItem/MP5K.lua",
		"InventoryItem/UZI.lua",
		"InventoryItem/AKSU.lua",
		"InventoryItem/Gewehr98.lua",
		"InventoryItem/M41Shotgun.lua",
		"InventoryItem/DoubleBarrelShotgun.lua",
		"InventoryItem/AA12.lua",
		"InventoryItem/Auto5.lua",
		"InventoryItem/M24Sniper.lua",
		"InventoryItem/M14SAW.lua",
		"InventoryItem/FNFAL.lua",
		"InventoryItem/M16A2.lua",
		"InventoryItem/M4Commando.lua",
		"InventoryItem/HK21.lua",
		"InventoryItem/FNMinimi.lua",
		"InventoryItem/MG42.lua",
		"InventoryItem/RPK74.lua",
		"InventoryItem/PSG1.lua",
		"InventoryItem/Winchester1894.lua",
		"InventoryItem/MP40.lua",
		"InventoryItem/BarretM82.lua",
		"InventoryItem/DragunovSVD.lua",
		"InventoryItem/AUG.lua",
	},
	'saved', 1696098210,
	'code_hash', 9005867977604204022,
})