UndefineClass('AR15')
DefineClass.AR15 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "AssaultRifle",
	Reliability = 80,
	ScrapParts = 10,
	Icon = "UI/Icons/Weapons/AR15",
	DisplayName = T(637295879064, --[[ModItemInventoryItemCompositeDef AR15 DisplayName]] "AR-15"),
	DisplayNamePlural = T(883735998026, --[[ModItemInventoryItemCompositeDef AR15 DisplayNamePlural]] "AR-15s"),
	Description = T(594405555108, --[[ModItemInventoryItemCompositeDef AR15 Description]] "Created to ensure the highest constitutional rights of self-defense and the possibility to bear a weapon that's easy as hell to convert to a fully-automatic one because a law-abiding citizen always needs one."),
	AdditionalHint = T(839983792761, --[[ModItemInventoryItemCompositeDef AR15 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> High Crit chance\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Low attack costs\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Highly modifiable\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> No Auto firing mode with standard Stock"),
	LargeItem = true,
	UnitStat = "Marksmanship",
	Cost = 1800,
	Caliber = "556",
	Damage = 17,
	AimAccuracy = 4,
	CritChanceScaled = 30,
	MagazineSize = 30,
	PenetrationClass = 2,
	WeaponRange = 24,
	OverwatchAngle = 1440,
	HandSlot = "TwoHanded",
	Entity = "Weapon_AR15",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"ScopeCOG",
				"ScopeCOGQuick",
				"LROptics",
				"LROpticsAdvanced",
				"ThermalScope",
				"ReflexSight",
				"ReflexSightAdvanced",
				"DefaultIronsight_AR15",
				"ImprovedIronsight_AR15",
				"Magnifier+ReflexSight",
			},
			'DefaultComponent', "DefaultIronsight_AR15",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagLargeFine",
				"CMag",
				"MagQuick",
				"SmallMag",
				"SmallMagFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
				"BarrelLong",
				"BarrelLongImproved",
				"BarrelHeavy",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy_AR_BurstOnly",
				"StockLight_AR_BurstOnly",
				"StockBump",
			},
			'DefaultComponent', "StockHeavy_AR_BurstOnly",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher",
				"VerticalGrip",
				"TacGrip",
				"Angled_Grip",
				"Bipod_Under",
				"Rail_Cover_3",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Rail",
			'AvailableComponents', {
				"Rail_Cover_0",
				"Rail_Cover_1",
				"Rail_Cover_2",
			},
			'DefaultComponent', "Rail_Cover_0",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"ImprovisedSuppressor",
				"Suppressor",
				"Suppressor_Anaconda",
				"MuzzleBooster",
			},
			'DefaultComponent', "Compensator",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Trigger",
			'AvailableComponents', {
				"DefaultTrigger",
				"LightweightTrigger",
				"HairTrigger",
				"HeavyDutyTrigger",
			},
			'DefaultComponent', "DefaultTrigger",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "General",
			'AvailableComponents', {
				"CaliberConversion556",
				"CaliberConversion762NATO",
				"CaliberConversion762WP",
			},
			'DefaultComponent', "CaliberConversion556",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 3000,
}

